# Generated by Django 4.2.13 on 2024-05-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicebook', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('engine_type', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicebook.servicebook')),
            ],
        ),
    ]
