# Generated by Django 4.2.13 on 2024-05-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
