# Generated by Django 4.2.13 on 2024-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_last_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_oil',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
