# Generated by Django 4.2.13 on 2024-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_engine_code_car_engine_oil'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='transmission_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_oil',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
