# Generated by Django 4.2.13 on 2024-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_transmission_code_car_transmission_oil'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='evidence_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='first_evidence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='foil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='hitch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
